### ISSUE TITLE
Meshing Checklist

### ISSUE THREAD

**Issue by nkemnitz** [seung-lab/PyChunkedGraph#78]
For future iterations:

- [ ] Add "remesh single object" functionality
- [ ] If a Lvl3+ node only has one child, copy the old manifest within the bucket - no need to download and re-upload.
- [ ] When collecting partners from adjacent chunks, it is not sufficient to use the direct-edge neighbors, we need all the siblings. (This avoids inconsistencies caused by ChunkedGraph generated at MIP0 and Meshing at MIP2)
- [ ] Generate gradually stronger simplified meshes for Lvl2 agglomerations. (Requires igneous changes to allow simplification of existing meshes)
- [ ] Check if it's sufficient to stitch simplified Lvl2 agglomerations together (and only rework the seams) to generate simplified Lvl3+ meshes, or if we have to simplify them from scratch using the unmodified Lvl2 meshes.
- [ ] Think about storing manifest content in ChunkedGraph, since the content is usually only 67 Bytes large (JSON) for each Lvl1-6 node. (requires Neuroglancer/Precomputed changes to lookup manifests from ChunkedGraph)

**Comment by sdorkenw** [comment]
#79 adds a manifest server (limited functionality)
